### ISSUE TITLE
Heroku app not working

### ISSUE THREAD

**Issue by Zyr00** [AndreVarandas/transportes-portugal-api#56]
**Describe the bug**
The [transportes-portugal.herokuapp.com/](https://transportes-portugal.herokuapp.com/) is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on [here](https://transportes-portugal.herokuapp.com/)
4. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/24510897/186870058-8e0fb44b-3cf8-47be-bc5d-bd936048d2a6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version 91.10.0esr

**Comment by AndreVarandas** [comment]
Hi @Zyr00 thanks for reaching out.

Unfortunately, the database provider I initially used has changed and requires a lot of new configuration. 
As for Heroku itself, they are dropping the free tier so I am removing support for it, was only meant to be a test environment anyway.

I'm updating the docs now, thank you!
